// Thin fetch wrapper for the NestJS API. Tokens live in localStorage; a 401 triggers one
// refresh attempt, and if that fails the session is cleared and 'auth:logout' is dispatched.

export type AccountType = 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';

export interface Account {
  id: string;
  code: string;
  name: string;
  type: AccountType;
  parentId: string | null;
  isActive: boolean;
}

export interface JournalLine {
  id: string;
  accountId: string;
  description: string | null;
  debit: string; // numeric columns arrive as strings, e.g. "10700.00"
  credit: string;
  lineNo: number;
}

export interface JournalEntry {
  id: string;
  entryNo: number;
  entryDate: string;
  description: string | null;
  reference: string | null;
  status: 'draft' | 'posted' | 'void';
  /** closing: generated by year-end closing; sales: posted by a billing note (issue or payment) */
  kind: 'manual' | 'closing' | 'sales';
  createdAt: string;
  lines: JournalLine[];
}

export interface TrialBalance {
  asOf: string | null;
  accounts: { accountId: string; code: string; name: string; type: AccountType; debit: number; credit: number }[];
  totalDebit: number;
  totalCredit: number;
  balanced: boolean;
}

export interface StatementSection {
  accounts: { accountId: string; code: string; name: string; amount: number }[];
  total: number;
}

export interface IncomeStatement {
  from: string | null;
  to: string | null;
  revenue: StatementSection;
  expenses: StatementSection;
  netIncome: number;
}

export interface BalanceSheet {
  asOf: string | null;
  assets: StatementSection;
  liabilities: StatementSection;
  /** total includes currentEarnings (revenue - expenses to date; there are no closing entries yet) */
  equity: StatementSection & { currentEarnings: number };
  totalLiabilitiesAndEquity: number;
  balanced: boolean;
}

export interface FiscalYearStatus {
  fiscalYearStartMonth: number;
  /** Books are locked through this date (latest closed fiscal year end), or null. */
  closedThrough: string | null;
  closings: {
    fiscalYearStart: string;
    fiscalYearEnd: string;
    netIncome: number;
    closedAt: string;
    closedBy: string | null;
    journalEntryId: string | null;
    entryNo: number | null;
  }[];
  nextClosable: {
    fiscalYearStart: string;
    fiscalYearEnd: string;
    canClose: boolean;
    revenue: number;
    expenses: number;
    netIncome: number;
    retainedEarningsAccount: { id: string; code: string; name: string } | null;
  } | null;
}

export interface Me {
  userId: string;
  email: string;
  fullName: string;
  tenantId: string;
  roles: string[];
}

export interface TenantDetail {
  id: string;
  name: string;
  slug: string;
  subscriptionStatus: string;
  company: Company | null;
  subscription: { status: string; trialEndsAt: string | null } | null;
}

export interface Company {
  name: string;
  taxId: string | null;
  /** 00000 = head office */
  branchCode: string;
  address: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  currency: string;
  fiscalYearStartMonth: number;
}

export interface Customer {
  id: string;
  name: string;
  taxId: string | null;
  branchCode: string | null;
  address: string | null;
  contactName: string | null;
  phone: string | null;
  email: string | null;
  creditDays: number;
  notes: string | null;
  isActive: boolean;
}

export type SalesDocType = 'quotation' | 'billing_note';
export type QuotationStatus = 'draft' | 'sent' | 'accepted' | 'rejected' | 'void';
export type BillingNoteStatus = 'draft' | 'issued' | 'paid' | 'void';
type DocRef = { id: string; docNo: string };
type AccountRef = { id: string; code: string; name: string };

export interface SalesDocumentRow {
  id: string;
  docNo: string;
  status: QuotationStatus | BillingNoteStatus;
  customerId: string;
  customerName: string;
  docDate: string;
  dueDate: string | null;
  reference: string | null;
  total: number;
  createdByName: string | null;
  /** quotation: the billing note made from it */
  billingNote?: DocRef | null;
  /** billing note: the quotation it came from */
  quotation?: DocRef | null;
}

export interface SalesDocument {
  id: string;
  docType: SalesDocType;
  docNo: string;
  status: QuotationStatus | BillingNoteStatus;
  customerId: string;
  /** Copied from the customer when the document was saved. */
  customer: { name: string; taxId: string | null; branchCode: string | null; address: string | null; contactName: string | null };
  docDate: string;
  /** quotation: valid until; billing note: due date */
  dueDate: string | null;
  reference: string | null;
  notes: string | null;
  vatRate: number;
  subtotal: number;
  discount: number;
  vatAmount: number;
  total: number;
  lines: { lineNo: number; description: string; quantity: number; unit: string | null; unitPrice: number; amount: number }[];
  createdByName: string | null;
  billingNote?: (DocRef & { status: BillingNoteStatus }) | null;
  quotation?: DocRef | null;
  revenueAccount?: AccountRef | null;
  journalEntry?: { id: string; entryNo: number } | null;
  paidDate?: string | null;
  paymentAccount?: AccountRef | null;
  paymentJournalEntry?: { id: string; entryNo: number } | null;
}

export type RoleName = 'Admin' | 'User';

export interface UserRow {
  id: string;
  email: string;
  fullName: string;
  isActive: boolean;
  lastLoginAt: string | null;
  createdAt: string;
  roles: string[];
}

export interface Invitation {
  id: string;
  email: string;
  fullName: string;
  role: string;
  expiresAt: string;
  createdAt: string;
  expired: boolean;
}

export interface InvitePreview {
  email: string;
  fullName: string;
  companyName: string;
  tenantSlug: string;
}

export type SubscriptionStatus = 'trialing' | 'active' | 'past_due' | 'canceled' | 'expired';

export interface BillingStatus {
  status: SubscriptionStatus;
  /** Trial over or unpaid: the API refuses writes (402) except billing. */
  readOnly: boolean;
  plan: { code: string; name: string; maxUsers: number | null } | null;
  trialEndsAt: string | null;
  currentPeriodEnd: string | null;
  cancelAtPeriodEnd: boolean;
}

export type PaymentAction = { type: 'redirect'; url: string } | { type: 'qr'; imageUrl: string; expiresAt: string | null };

export interface BillingOverview extends BillingStatus {
  vatRate: number;
  /** canSimulate: test-mode gateway, payments can be completed without a real bank app. */
  gateway: { provider: string; canSimulate: boolean };
  plans: { code: string; name: string; maxUsers: number | null; priceMonthly: number; vatAmount: number; total: number }[];
  invoices: {
    id: string;
    invoiceNo: string;
    description: string | null;
    subtotal: number;
    vatAmount: number;
    amount: number;
    status: 'draft' | 'open' | 'paid' | 'void';
    paymentStatus: 'pending' | 'succeeded' | 'failed' | null;
    /** How to pay this open invoice while its payment is pending (e.g. the PromptPay QR). */
    paymentAction: { type: 'redirect' | 'qr'; url: string; expiresAt: string | null } | null;
    issuedAt: string | null;
    paidAt: string | null;
    periodStart: string | null;
    periodEnd: string | null;
  }[];
}

export interface Tokens {
  accessToken: string;
  refreshToken: string;
}

export class ApiError extends Error {
  readonly status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

const ACCESS_KEY = 'acc.accessToken';
const REFRESH_KEY = 'acc.refreshToken';

export const session = {
  get access() {
    return localStorage.getItem(ACCESS_KEY);
  },
  get refresh() {
    return localStorage.getItem(REFRESH_KEY);
  },
  save(t: Tokens) {
    localStorage.setItem(ACCESS_KEY, t.accessToken);
    localStorage.setItem(REFRESH_KEY, t.refreshToken);
  },
  clear() {
    localStorage.removeItem(ACCESS_KEY);
    localStorage.removeItem(REFRESH_KEY);
  },
};

/** Thai text for server messages a user is likely to see; anything else is shown as sent. */
const THAI_MESSAGES: Record<string, string> = {
  'Invalid credentials': 'รหัสบริษัท อีเมล หรือรหัสผ่านไม่ถูกต้อง',
  'Slug is already taken': 'รหัสบริษัทนี้ถูกใช้แล้ว',
  'Requires role: Admin': 'เฉพาะผู้ดูแลระบบ (Admin) เท่านั้น',
  'A user with this email already exists': 'มีผู้ใช้อีเมลนี้อยู่แล้ว',
  'An invitation for this email is already pending': 'มีคำเชิญของอีเมลนี้ค้างอยู่แล้ว',
  'Invitation is invalid or has expired': 'ลิงก์คำเชิญไม่ถูกต้อง ถูกยกเลิก หรือหมดอายุแล้ว',
  'At least one active Admin is required': 'ต้องมีผู้ดูแลระบบ (Admin) ที่ใช้งานอยู่อย่างน้อย 1 คน',
  'You cannot deactivate yourself': 'ปิดการใช้งานบัญชีของตัวเองไม่ได้',
  'Subscription inactive': 'บัญชีอยู่ในโหมดอ่านอย่างเดียว ต้องชำระค่าบริการก่อนจึงจะบันทึกหรือแก้ไขข้อมูลได้',
  'Plan user limit reached': 'จำนวนผู้ใช้ครบตามแพ็กเกจแล้ว อัปเกรดแพ็กเกจเพื่อเพิ่มผู้ใช้',
  'Charge not found': 'ไม่พบรายการชำระเงิน',
  'Payment simulation is only available with a test-mode payment gateway': 'จำลองการชำระเงินได้เฉพาะโหมดทดสอบ',
  'Too many failed login attempts': 'ใส่รหัสผ่านผิดหลายครั้งเกินไป บัญชีนี้ถูกล็อกชั่วคราว กรุณาลองใหม่ภายใน 15 นาที',
  'Too many requests': 'มีการเรียกใช้งานถี่เกินไป กรุณารอสักครู่แล้วลองใหม่',
  'Period is closed': 'ปีบัญชีนี้ปิดบัญชีแล้ว บันทึกหรือยกเลิกรายการที่ลงวันที่ในช่วงนี้ไม่ได้',
  'The fiscal year has not ended yet': 'ปีบัญชียังไม่สิ้นสุด ปิดบัญชีได้หลังวันสิ้นปีบัญชี',
  'Closing entries are reversed by reopening the fiscal year': 'รายการปิดบัญชียกเลิกได้โดยการเปิดปีบัญชีอีกครั้งเท่านั้น',
  'Retained earnings account 3100 not found': 'ไม่พบบัญชี 3100 กำไร (ขาดทุน) สะสม',
  'Customer not found': 'ไม่พบลูกค้า',
  'Customer is inactive': 'ลูกค้ารายนี้ถูกปิดใช้งานแล้ว',
  'Discount exceeds the subtotal': 'ส่วนลดมากกว่ายอดรวม',
  'Document total is too large': 'ยอดรวมเอกสารสูงเกินไป',
  'Only draft documents can be edited': 'แก้ไขได้เฉพาะเอกสารสถานะร่าง',
  'Only accepted quotations can be billed': 'สร้างใบวางบิลได้เฉพาะใบเสนอราคาที่ลูกค้าตอบรับแล้ว',
  'Quotation already billed': 'ใบเสนอราคานี้สร้างใบวางบิลแล้ว',
  'Void the billing note made from this quotation first': 'ต้องยกเลิกใบวางบิลที่สร้างจากใบเสนอราคานี้ก่อน',
  'Only draft billing notes can be issued': 'ออกใบวางบิลได้เฉพาะสถานะร่าง',
  'Only issued billing notes can be paid': 'บันทึกรับชำระได้เฉพาะใบวางบิลที่ออกแล้ว',
  'Billing note total must be greater than zero': 'ยอดใบวางบิลต้องมากกว่าศูนย์',
  'Payment date is before the billing note date': 'วันที่รับชำระต้องไม่ก่อนวันที่ใบวางบิล',
  'Payment account must be an active asset account': 'บัญชีรับเงินต้องเป็นบัญชีสินทรัพย์ที่ใช้งานอยู่',
  'Revenue account must be an active revenue account': 'บัญชีรายได้ต้องเป็นบัญชีหมวดรายได้ที่ใช้งานอยู่',
  'Paid billing notes cannot be voided': 'ใบวางบิลที่ชำระแล้วยกเลิกไม่ได้',
  'Billing note entries are reversed by voiding the billing note': 'รายการนี้มาจากใบวางบิล ยกเลิกได้ที่หน้าใบวางบิล',
  'Due date is before the billing note date': 'วันครบกำหนดต้องไม่ก่อนวันที่ใบวางบิล',
  'Valid-until date is before the quotation date': 'วันยืนราคาต้องไม่ก่อนวันที่ใบเสนอราคา',
};

async function errorFrom(res: Response): Promise<ApiError> {
  let message = `${res.status} ${res.statusText}`;
  try {
    const body = await res.json();
    // Nest validation errors come back as an array of messages.
    if (body?.message) message = Array.isArray(body.message) ? body.message.join(', ') : String(body.message);
  } catch {
    // not JSON; keep the status text
  }
  return new ApiError(res.status, THAI_MESSAGES[message] ?? message);
}

let refreshing: Promise<boolean> | null = null;

/** Concurrent 401s share one refresh request. */
function refreshTokens(): Promise<boolean> {
  const refreshToken = session.refresh;
  if (!refreshToken) return Promise.resolve(false);
  refreshing ??= fetch('/api/v1/auth/refresh', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refreshToken }),
  })
    .then(async (res) => {
      if (!res.ok) return false;
      session.save(await res.json());
      return true;
    })
    .catch(() => false)
    .finally(() => {
      refreshing = null;
    });
  return refreshing;
}

export async function api<T>(path: string, options: { method?: string; body?: unknown; auth?: boolean } = {}): Promise<T> {
  const { method = 'GET', body, auth = true } = options;

  const send = () => {
    const headers: Record<string, string> = {};
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    if (auth && session.access) headers.Authorization = `Bearer ${session.access}`;
    return fetch(`/api/v1${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  };

  let res = await send();
  if (res.status === 401 && auth) {
    if (await refreshTokens()) {
      res = await send();
    }
    if (res.status === 401) {
      session.clear();
      window.dispatchEvent(new Event('auth:logout'));
    }
  }
  if (!res.ok) throw await errorFrom(res);
  return res.status === 204 ? (undefined as T) : res.json();
}
